---
environment_variables:
  IMAMPSYNC_VERSION: "3.12-1"
git:
  branch: main
triggers:
  github_push: true
clean_workspace: true
builders:
  - docker
docker_name: drive/imapsync
docker_tags:
  - "${IMAPSYNC_VERSION}"
  - "latest"
docker_no_cache: true
